#!/usr/bin/env python3
"""
GitHub Auto-commit for Obsidian RSI
변경사항 자동 감지 및 커밋/푸시
"""

import subprocess
from pathlib import Path
from datetime import datetime
import sys

def run_git_command(command, cwd):
    """
    Git 명령 실행
    """
    try:
        result = subprocess.run(
            command,
            cwd=cwd,
            capture_output=True,
            text=True,
            check=True
        )
        return True, result.stdout.strip()
    except subprocess.CalledProcessError as e:
        return False, e.stderr.strip()


def check_git_status(vault_path):
    """
    Git 상태 확인
    """
    success, output = run_git_command(['git', 'status', '--porcelain'], vault_path)
    
    if not success:
        return None, "Git repository not initialized or error occurred"
    
    if not output:
        return [], "No changes detected"
    
    # 변경 파일 목록
    changes = []
    for line in output.split('\n'):
        if line.strip():
            status = line[:2].strip()
            file_path = line[3:].strip()
            changes.append({
                'status': status,
                'file': file_path
            })
    
    return changes, None


def categorize_changes(changes):
    """
    변경사항 카테고리화
    """
    categories = {
        'added': [],
        'modified': [],
        'deleted': [],
        'renamed': []
    }
    
    for change in changes:
        status = change['status']
        file_path = change['file']
        
        if status in ['A', '??']:
            categories['added'].append(file_path)
        elif status == 'M':
            categories['modified'].append(file_path)
        elif status == 'D':
            categories['deleted'].append(file_path)
        elif status == 'R':
            categories['renamed'].append(file_path)
    
    return categories


def generate_commit_message(categories):
    """
    자동 커밋 메시지 생성
    """
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    # 변경 요약
    summary_parts = []
    
    if categories['added']:
        summary_parts.append(f"Add {len(categories['added'])} file(s)")
    if categories['modified']:
        summary_parts.append(f"Update {len(categories['modified'])} file(s)")
    if categories['deleted']:
        summary_parts.append(f"Delete {len(categories['deleted'])} file(s)")
    if categories['renamed']:
        summary_parts.append(f"Rename {len(categories['renamed'])} file(s)")
    
    summary = ", ".join(summary_parts)
    
    # 상세 메시지 구성
    message = f"[Auto RSI] {summary}\n\nTimestamp: {timestamp}\n"
    
    # 파일별 상세
    if categories['added']:
        message += f"\nAdded:\n"
        for f in categories['added'][:5]:  # 최대 5개
            message += f"  - {f}\n"
        if len(categories['added']) > 5:
            message += f"  ... and {len(categories['added'])-5} more\n"
    
    if categories['modified']:
        message += f"\nModified:\n"
        for f in categories['modified'][:5]:
            message += f"  - {f}\n"
        if len(categories['modified']) > 5:
            message += f"  ... and {len(categories['modified'])-5} more\n"
    
    if categories['deleted']:
        message += f"\nDeleted:\n"
        for f in categories['deleted'][:5]:
            message += f"  - {f}\n"
        if len(categories['deleted']) > 5:
            message += f"  ... and {len(categories['deleted'])-5} more\n"
    
    message += "\n---\nGenerated by Auto RSI GitHub Auto-commit"
    
    return message


def git_add_all(vault_path):
    """
    모든 변경사항 스테이징
    """
    success, output = run_git_command(['git', 'add', '.'], vault_path)
    return success, output


def git_commit(vault_path, message):
    """
    커밋 실행
    """
    success, output = run_git_command(['git', 'commit', '-m', message], vault_path)
    return success, output


def git_push(vault_path, remote='origin', branch='main'):
    """
    푸시 실행
    """
    success, output = run_git_command(['git', 'push', remote, branch], vault_path)
    return success, output


def main():
    """
    메인 실행 함수
    """
    print("="*60)
    print("GitHub Auto-commit for Obsidian RSI")
    print("="*60)
    
    # Vault 경로 설정 (수정 필요)
    vault_path = Path(r"C:\Users\win10_original\claude-vault")
    
    if not vault_path.exists():
        print(f"❌ Error: Vault not found at {vault_path}")
        print("Please update vault_path in the script.")
        return
    
    print(f"\n📂 Vault: {vault_path}")
    
    # Git 저장소 확인
    git_dir = vault_path / ".git"
    if not git_dir.exists():
        print("❌ Error: Not a git repository")
        print("Please initialize git repository first:")
        print(f"  cd {vault_path}")
        print("  git init")
        return
    
    # 변경사항 확인
    print("\n🔍 Checking for changes...")
    changes, error = check_git_status(vault_path)
    
    if error:
        print(f"ℹ️ {error}")
        return
    
    if not changes:
        print("✓ No changes to commit")
        return
    
    print(f"✓ Found {len(changes)} changed file(s)")
    
    # 변경사항 카테고리화
    categories = categorize_changes(changes)
    
    print("\n📊 Changes summary:")
    if categories['added']:
        print(f"  ➕ Added: {len(categories['added'])} file(s)")
    if categories['modified']:
        print(f"  ✏️ Modified: {len(categories['modified'])} file(s)")
    if categories['deleted']:
        print(f"  ❌ Deleted: {len(categories['deleted'])} file(s)")
    if categories['renamed']:
        print(f"  🔄 Renamed: {len(categories['renamed'])} file(s)")
    
    # 커밋 메시지 생성
    commit_message = generate_commit_message(categories)
    
    print("\n📝 Commit message:")
    print("-" * 60)
    print(commit_message)
    print("-" * 60)
    
    # 사용자 확인 (자동 모드면 스킵)
    if '--auto' not in sys.argv:
        response = input("\nProceed with commit? (y/n): ")
        if response.lower() != 'y':
            print("❌ Commit cancelled")
            return
    
    # Git add
    print("\n📦 Staging changes...")
    success, output = git_add_all(vault_path)
    
    if not success:
        print(f"❌ Error staging changes: {output}")
        return
    
    print("✓ Changes staged")
    
    # Git commit
    print("\n💾 Committing...")
    success, output = git_commit(vault_path, commit_message)
    
    if not success:
        print(f"❌ Error committing: {output}")
        return
    
    print("✓ Changes committed")
    
    # Git push (선택적)
    if '--push' in sys.argv or '--auto' in sys.argv:
        print("\n📤 Pushing to remote...")
        
        # 브랜치 확인
        success, current_branch = run_git_command(['git', 'branch', '--show-current'], vault_path)
        
        if not success:
            print(f"⚠️ Could not determine current branch, using 'main'")
            current_branch = 'main'
        
        success, output = git_push(vault_path, 'origin', current_branch)
        
        if not success:
            print(f"⚠️ Push failed: {output}")
            print("You may need to push manually")
        else:
            print("✓ Changes pushed to remote")
    else:
        print("\nℹ️ Changes committed locally (not pushed)")
        print("Use --push flag to push automatically")
    
    print("\n" + "="*60)
    print("✨ Auto-commit completed!")
    print("="*60)


if __name__ == "__main__":
    """
    사용법:
    
    1. 기본 실행 (확인 후 커밋):
       python github_auto_commit.py
    
    2. 자동 커밋 (확인 없이):
       python github_auto_commit.py --auto
    
    3. 커밋 + 푸시:
       python github_auto_commit.py --push
    
    4. 완전 자동 (커밋 + 푸시):
       python github_auto_commit.py --auto --push
    """
    main()
