/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BrainTwinAutoRSI
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: false,
  scheduleTime: "09:00",
  scheduleType: "daily",
  scheduleDayOfWeek: 1,
  // Monday
  showNotifications: true
};
var AutoRSISettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "BrainTwin Auto RSI Settings" });
    new import_obsidian.Setting(containerEl).setName("Enable Auto RSI").setDesc("Automatically run RSI analysis on schedule").addToggle((toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
      this.plugin.settings.enabled = value;
      await this.plugin.saveSettings();
      if (value) {
        this.plugin.startScheduler();
      } else {
        this.plugin.stopScheduler();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Schedule Type").setDesc("Run daily or weekly").addDropdown((dropdown) => dropdown.addOption("daily", "Daily").addOption("weekly", "Weekly").setValue(this.plugin.settings.scheduleType).onChange(async (value) => {
      this.plugin.settings.scheduleType = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.scheduleType === "weekly") {
      new import_obsidian.Setting(containerEl).setName("Day of Week").setDesc("Which day to run the analysis").addDropdown((dropdown) => dropdown.addOption("0", "Sunday").addOption("1", "Monday").addOption("2", "Tuesday").addOption("3", "Wednesday").addOption("4", "Thursday").addOption("5", "Friday").addOption("6", "Saturday").setValue(String(this.plugin.settings.scheduleDayOfWeek)).onChange(async (value) => {
        this.plugin.settings.scheduleDayOfWeek = parseInt(value);
        await this.plugin.saveSettings();
      }));
    }
    new import_obsidian.Setting(containerEl).setName("Schedule Time").setDesc("Time to run analysis (HH:MM format, 24-hour)").addText((text) => text.setPlaceholder("09:00").setValue(this.plugin.settings.scheduleTime).onChange(async (value) => {
      this.plugin.settings.scheduleTime = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Show Notifications").setDesc("Show notification when analysis completes").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (value) => {
      this.plugin.settings.showNotifications = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Manual Run").setDesc("Run analysis now (for testing)").addButton((button) => button.setButtonText("Run Now").onClick(() => {
      this.plugin.runAnalysis();
    }));
  }
};

// analyzer.ts
var VaultAnalyzer = class {
  constructor(vault) {
    this.vault = vault;
  }
  async analyze() {
    const files = this.vault.getMarkdownFiles();
    const stats = {
      totalNotes: files.length,
      totalLinks: 0,
      isolatedNotes: 0,
      recentlyModified: []
    };
    for (const file of files) {
      const content = await this.vault.cachedRead(file);
      const links = this.extractLinks(content);
      stats.totalLinks += links.length;
      if (links.length === 0) {
        stats.isolatedNotes++;
      }
    }
    const oneDayAgo = Date.now() - 24 * 60 * 60 * 1e3;
    stats.recentlyModified = files.filter((f) => f.stat.mtime > oneDayAgo).map((f) => f.basename).slice(0, 10);
    return stats;
  }
  extractLinks(content) {
    const linkRegex = /\[\[([^\]]+)\]\]/g;
    const links = [];
    let match;
    while ((match = linkRegex.exec(content)) !== null) {
      links.push(match[1]);
    }
    return links;
  }
};

// scheduler.ts
var RSIScheduler = class {
  constructor(callback) {
    this.intervalId = null;
    this.callback = callback;
  }
  start(scheduleTime, scheduleType, dayOfWeek) {
    this.stop();
    const [hours, minutes] = scheduleTime.split(":").map(Number);
    this.intervalId = window.setInterval(() => {
      const now = new Date();
      const currentHours = now.getHours();
      const currentMinutes = now.getMinutes();
      const currentDay = now.getDay();
      if (currentHours === hours && currentMinutes === minutes) {
        if (scheduleType === "daily") {
          this.callback();
        } else if (scheduleType === "weekly" && currentDay === dayOfWeek) {
          this.callback();
        }
      }
    }, 6e4);
    console.log(`Scheduler started: ${scheduleType} at ${scheduleTime}`);
  }
  stop() {
    if (this.intervalId !== null) {
      window.clearInterval(this.intervalId);
      this.intervalId = null;
      console.log("Scheduler stopped");
    }
  }
};

// main.ts
var BrainTwinAutoRSI = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.analyzer = new VaultAnalyzer(this.app.vault);
    this.scheduler = new RSIScheduler(() => this.runAnalysis());
    this.addSettingTab(new AutoRSISettingTab(this.app, this));
    this.addRibbonIcon("brain-circuit", "Run Auto RSI", () => {
      this.runAnalysis();
    });
    this.addCommand({
      id: "run-auto-rsi",
      name: "Run Auto RSI Now",
      callback: () => this.runAnalysis()
    });
    if (this.settings.enabled) {
      this.startScheduler();
    }
    console.log("BrainTwin Auto RSI loaded");
  }
  onunload() {
    this.stopScheduler();
    console.log("BrainTwin Auto RSI unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  startScheduler() {
    this.scheduler.start(
      this.settings.scheduleTime,
      this.settings.scheduleType,
      this.settings.scheduleDayOfWeek
    );
    new import_obsidian2.Notice("Auto RSI scheduler started");
  }
  stopScheduler() {
    this.scheduler.stop();
  }
  async runAnalysis() {
    if (this.settings.showNotifications) {
      new import_obsidian2.Notice("\u{1F916} Running Auto RSI analysis...");
    }
    try {
      const stats = await this.analyzer.analyze();
      const message = this.formatResults(stats);
      if (this.settings.showNotifications) {
        new import_obsidian2.Notice(message, 1e4);
      }
      console.log("Auto RSI Analysis Results:", stats);
    } catch (error) {
      console.error("Auto RSI analysis failed:", error);
      new import_obsidian2.Notice("\u274C Auto RSI analysis failed");
    }
  }
  formatResults(stats) {
    return `\u2705 Auto RSI Complete!
\u{1F4DD} Notes: ${stats.totalNotes}
\u{1F517} Links: ${stats.totalLinks}
\u26A0\uFE0F Isolated: ${stats.isolatedNotes}
\u{1F4C5} Modified today: ${stats.recentlyModified.length}`;
  }
};
